import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={
        "{geistSans.variable} ${geistMono.variable} h-full antialiased"
      }
    >
      <body className="min-h-full flex flex-col">
        <header className="min-h-16 flex items-center px-6 bg-blue-600 text-white">
          <span className="font-semibold">Header</span>
        </header>
        <nav className="min-h-12 flex items-center gap-4 px-6 bg-amber-400 text-black">
          <Link href="/" className="hover:underline">
            Home
          </Link>
          <Link href="/Login" className="hover:underline">
            Login
          </Link>
          <Link href="/vender" className="hover:underline">
            Vender
          </Link>
        </nav>
        <main className="flex-1 flex flex-col bg-zinc-100 dark:bg-zinc-900">
          {children}
        </main>
        <footer className="min-h-16 flex items-center justify-center px-6 bg-emerald-700 text-white">
          <span>Footer</span>
        </footer>
      </body>
    </html>
  );
}
